version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    # workaround
    #user: root
    #command: "php-fpm -R"
    #command: "sudo /usr/sbin/sshd -De"
    # workaround
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      # user: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - "${HOME_PATH}/${PROJECT_NAME}/code:/var/www/html"

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    #user: root
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/webroot
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - "${HOME_PATH}/${PROJECT_NAME}/code:/var/www/html"
      - "${HOME_PATH}/${PROJECT_NAME}/cake4php.conf.tmpl:/etc/gotpl/presets/cake4php.conf.tmpl"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
      #- "traefik.http.middlewares.mid1-${PROJECT_NAME}_nginx.basicauth.users=${BASIC_AUTH}"
      #- "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=mid1-${PROJECT_NAME}_nginx@docker"

#  mailhog:
#    image: mailhog/mailhog
#    container_name: "${PROJECT_NAME}_mailhog"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
#      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  #  redis:
  #    container_name: "${PROJECT_NAME}_redis"
  #    image: wodby/redis:$REDIS_TAG

  adminer:
    container_name: "${PROJECT_NAME}_adminer"
    image: wodby/adminer:$ADMINER_TAG
    environment:
## For PostgreSQL:
##      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"


#  memcached:
#    container_name: "${PROJECT_NAME}_memcached"
#    image: wodby/memcached:$MEMCACHED_TAG

#  rsyslog:
#    container_name: "${PROJECT_NAME}_rsyslog"
#    image: wodby/rsyslog:$RSYSLOG_TAG

#  chrome:
#    image: selenium/standalone-chrome:$SELENIUM_CHROME_TAG
#    container_name: "${PROJECT_NAME}_chrome"
#    volumes:
#      - /dev/shm:/dev/shm
#    entrypoint:
#      - chromedriver
#      - "--no-sandbox"
#      - "--disable-dev-shm-usage"
#      - "--log-path=/tmp/chromedriver.log"
#      - "--verbose"
#      - "--whitelisted-ips="

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    # -l "hideContainer=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"
      - "traefik.http.middlewares.mid1-${PROJECT_NAME}_portainer.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.${PROJECT_NAME}_portainer.middlewares=mid1-${PROJECT_NAME}_portainer@docker"

  ide:
    image: codercom/code-server:latest
    container_name: "${PROJECT_NAME}_ide"
    #user: coder
    command: --auth none
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.${PROJECT_NAME}_ide.loadbalancer.server.port=8080"
      #- "traefik.http.routers.${PROJECT_NAME}_ide.rule=Host(`ide.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_ide.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_https_ide.entrypoints=web-secure"
      - "traefik.http.routers.${PROJECT_NAME}_https_ide.rule=Host(`ide.${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_https_ide.tls=true"
      #- "traefik.http.middlewares.mid1-${PROJECT_NAME}_ide.basicauth.users=${BASIC_AUTH}"
      #- "traefik.http.routers.${PROJECT_NAME}_ide.middlewares=mid1-${PROJECT_NAME}_ide@docker"
    volumes:
      - "${HOME_PATH}/${PROJECT_NAME}/code:/home/coder/project"
      - "${HOME_PATH}/${PROJECT_NAME}/.coder/share/code-server:/home/coder/.local/share/code-server"

#volumes:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:

#volumes:
#  mariadbdata:
#    driver: local
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:
